# Generated by Django 5.2.3 on 2025-06-19 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('honorario_total_bruto', models.IntegerField()),
                ('tipo_pago', models.TextField()),
                ('viaticos', models.TextField()),
                ('observaciones', models.TextField()),
                ('enlace_funciones', models.TextField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('grado_eus', models.IntegerField()),
                ('descripcion_funcion', models.TextField()),
                ('calificacion_profesional', models.TextField()),
            ],
            options={
                'db_table': 'funcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_emisor', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'mensaje_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.TextField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntaBloqueada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('razon', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'preguntas_bloqueadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionChat',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('nombre_sesion', models.TextField()),
            ],
            options={
                'db_table': 'sesion_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiempoContrato',
            fields=[
                ('id_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('anho', models.IntegerField()),
                ('mes', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('region', models.TextField()),
            ],
            options={
                'db_table': 'tiempo_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerminoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terminos_excluidos',
            },
        ),
    ]
