# Generated by Django 5.2.3 on 2025-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prompt_sistema', models.TextField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contextos_prompt',
            },
        ),
    ]
